package com.sorted.lac.service.enums;

public enum RegionalEnum {

    GERAL_TRANSPORTE_FORA_DO_ESTADO(1),
    SEDE(2),
    COORDENADORIA_DE_DESENVOLVIMENTO_AMBIENTAL_DA_GRANDE_FLORIANOPOLIS(3),
    COORDENADORIA_DE_DESENVOLVIMENTO_AMBIENTAL_DE_CRICIUMA(19),
    COORDENADORIA_DE_DESENVOLVIMENTO_AMBIENTAL_DE_BLUMENAU(20),
    COORDENADORIA_DE_DESENVOLVIMENTO_AMBIENTAL_DE_JOINVILLE(21),
    COORDENADORIA_DE_DESENVOLVIMENTO_AMBIENTAL_DE_CANOINHAS(22),
    COORDENADORIA_DE_DESENVOLVIMENTO_AMBIENTAL_DE_LAGES(23),
    COORDENADORIA_DE_DESENVOLVIMENTO_AMBIENTAL_DE_JOACABA(24),
    COORDENADORIA_DE_DESENVOLVIMENTO_AMBIENTAL_DE_CHAPECO(25),
    COORDENADORIA_DE_DESENVOLVIMENTO_AMBIENTAL_DE_TUBARAO(26),
    COORDENADORIA_DE_DESENVOLVIMENTO_AMBIENTAL_DE_ITAJAI(27),
    COORDENADORIA_DE_DESENVOLVIMENTO_AMBIENTAL_DE_RIO_DO_SUL(28),
    COORDENADORIA_DE_DESENVOLVIMENTO_AMBIENTAL_DE_SAO_MIGUEL_DO_OESTE(29),
    COORDENADORIA_DE_DESENVOLVIMENTO_AMBIENTAL_DE_CACADOR(30),
    COORDENADORIA_DE_DESENVOLVIMENTO_AMBIENTAL_DE_MAFRA(39),
    MINISTERIO_PUBLICO(43),
    SECRETARIA_DE_DESENVOLVIMENTO_SUSTENTAVEL_SDS(45),
    TRIBUNAL_DE_CONTAS_DE_SANTA_CATARINA(46),
    COORDENADORIA_DE_DESENVOLVIMENTO_AMBIENTAL_DE_JARAGUA_DO_SUL(48),
    COORDENADORIA_DE_DESENVOLVIMENTO_AMBIENTAL_DE_CONCORDIA(50);

    private Integer valor;

    private RegionalEnum(Integer valor) {
        this.valor = valor;
    }

    public Integer getValor() {
        return valor;
    }

}
