package com.sorted.lac.service.enums;

import java.util.Arrays;
import java.util.List;

public enum TipoDocumentoEnum {
    NAO_DEFINIDO_AINDA(0), HISTORICO_RESUMO_PROCESSO(1), FCEI_FORMULARIO_DE_CARACTERIZACAO_DO_EMPREENDIMENTO(13), COPIA_AUTENTICADA_OU_O_DOCUMENTO_ORIGINAL_DE_PROCURACAO(63), RECURSOS(328), LICENCA_AMBIENTAL_PREVIA_LAP(380), LICENCA_AMBIENTAL_DE_INSTALACAO_LAI(381), LICENCA_AMBIENTAL_DE_OPERACAO_LAO(382), LICENCA_AMBIENTAL_PREVIA_COM_DISPENSA_DE_IMPLANTACAO_LAP_LAI(383), AUTORIZACAO_AMBIENTAL(384), CERTIDAO_DE_ATIVIDADE_NAO_CONSTANTE_NA_RESOLUCAO_CONSEMA(385), CERTIFICADO_DE_RECONHECIMENTO_DE_LABORATORIO(386), FORMULARIO_DE_INFORMACAO_DA_EQUIPE_DO_LICENCIAMENTO_PARA_A_CTCA(387), RECIBO_DE_DOCUMENTOS(400), IN_INSTRUCAO_NORMATIVA(401), DOCUMENTO_DE_ARRECADACAO_DE_RECEITAS_ESTADUAIS_DARE(695), INSCRICAO_OCUPACAO_PATRIMONIAL_AREA_DE_MARINHA(711), CERTIDAO_CONFORMIDADE_AMBIENTAL(892), ATA_DE_ELEICAO_DA_ULTIMA_SOCIEDADE(972), CNPJ_CPF_COPIA(973), TRANSCRICAO_OU_MATRICULA_CARTORIO(1206), DARE_QUITADO_RELATIVO_A_TFASC_DO_ANO_VIGENTE(1220), DOCUMENTO_DE_ARRECADACAO_DE_RECEITAS_ESTADUAIS_DARE_COMPLEMENTAR(1224), TERMO_DE_AJUSTAMENTO_DE_CONNDUTAS_COPIA(1225), REQUISICAO_PARA_FORMALIZACAO_CORRETIVA(1250), DOCUMENTO_DE_ARRECADACAO_DE_RECEITAS_ESTADUAIS_DARE_LABORATORIO(1296), CADASTRO_AMBIENTAL_RURAL(1330), ANOTACAO_DE_RESPONSABILIDADE_TECNICA(1350), ARQUIVO_SHAPEFILE(1372), LICENCA_ASSINADA_DIGITALMENTE(1387), DECLARACAO_DE_ATIVIDADE_NAO_SUJEITA_AO_LICENCIAMENTO_AMBIENTAL(1389), BOLETO_BANCARIO_GERADO_PREFEITURA(1390), COPIA_AUTENTICADA_BOLETO_PREFEITURA(1391), OFICIO_INDEFERIMENTO(1392), CERTIDAO_OU_LICENCA(1393), PECA_EMPREENDEDOR(1905),

    //-------------------- TEM QUE REVER ESSES CODIGOS PRA BATER NO BANCO
    LOCALIZACAO_COM_COORDENADAS_GEOGRAFICAS(1397), ANOTACOES_RESP_TECNICA_OU_FUNCAO_TECNICA(1398), BRACATINGAL_AMBITO_FAMILIAR(1399), INVENTARIO_FITOSSOCIOLOGICO_DA_AREA(1400), ENRIQUECIMENTO_EM_AREA_ESTAGIO_INICIAL(1401), ENRIQUECIMENTO_AGRICULTURA_FAMILIAR(1402), TABELA_COORDENA_IMOVEL_VERTICES_ENRIQUECIMENTO(1403), CRONOGRAMA_EXEC_PREVISTO(1406), OUTROS_DOCS_COMPROVAR_PLANTIO(1397), ESTIMATIVA_QTD_EXEMPLARES(1398), QTD_A_SER_PLANTADA_OU_INTRODUZIDAS(1399), ART_AFT(1399),
    //-------------------- TEM QUE REVER ESSES CODIGOS PRA BATER NO BANCO

    URL_PARECER_EXTERNO(1404), URL_DECLARACAO_EXTERNO(1405), DECLARACAO_DE_AGRICULTURA_FAMILIAR(1406), TERMO_PARA_USO_DE_FOGO(1407), LICENCA_ASSINADA(1438), DOCUMENTO_ASSINADO(1476), LAC_AVICULTURA(1477), ARQUIVO_SHAPEFILE_EMPREENDIMENTO(1506), PLANILHA_INVENTARIO_CSV(1507), ARQUIVO_SHAPEFILE_PROJETO(1513), SHAPEFILE_AREA_EMPREENDIMENTO(1552), LAC_TPP(1622), RENLAO_AUTO_LINHAS_TRANS(1623), LAC_TPP_CERTIFICADO_REGISTRO_ALVARA_AUTORIZACAO(1626), LAC_TPP_CERTIFICADO_REGISTRO__ENERGIA_NUCLEAR(1627), SHAPEFILE_POLIG_LIMITES_IMOVEL(1647), SHAPEFILE_RRPN_ESTADUAL(1643), SHAPEFILE_POLIG_LIMITES_IMOVEL2(1680), AUDITORIA(1684), PROJETO_DE_CONTROLE_AMBIENTAL(1741), SHAPEFILE_POLIG_LIMITES_IMOVEL3(1744), LAC_ANTENA(1747), LAC_ANTENA_COMPARTILHAMENTO(1752), SHAPEFILE_POLIG_LIMITES_IMOVEL4(1797), CERTIDAO_DE_ATIVIDADE_NAO_CONSTANTE_NA_RESOLUCAO_CONSEMA_AUTOMATICA(1806), AUA_QUEIMADA(1820), FCEI_CERTIDAO(1821), FCEI_EXPLORACAO(1822), FCEI_LICENCIAMENTO(1823), FCEI_OUTROS(1824), FCE_PLANTIO(1825), RELATORIO_VISTORIA_ASSINATURA(1826), INFORMACAO_TECNICA_ASSINATURA(1827), PARECER_TECNICO_ASSINATURA(1828), OFICIO(1829), PARECER_TECNICO_RASCUNHO(1830), //PECA_
    LICENCA_RASCUNHO(1831), //PECA_
    CONFIRMACAO_RECEBIMENTO_SOLICITACAO_COMPLEMENTAR(1832), RECIBO_ENVIO_DOCUMENTACAO_COMPLEMENTAR(1833), EVENTO_ALTERACAO_EQUIPE(1834), //PECA_
    EVENTO_ALTERACAO_EMPREENDIMENTO(1836), //PECA_
    EVENTO_RECUSA(1837), //PECA_
    EVENTO_RECUSA_DOCS_PROTOCOLO(1838), //PECA_
    EVENTO_ANEXO_DOCUMENTOS(1839), //PECA_
    REGISTRO_DE_EVENTO_MOTIVO(1840), //PECA_
    ANEXO_OFICIO_ALTERACAO_AUC_NO_SINAFLOR(1841), RCE_FAUNA(1843), LAC_FAUNA(1844), LAC_SUINOCULTURA(1865), RECURSO_ADMINISTRATIVO(1880), RECURSO_ANEXOS(1881), PECA(1884), //PECA_
    COMPROVANTE_RECEBIMENTO(1885), RELATORIO_FAUNA(1886), SOLICITACAO_INCLUSAO_EQUIPE(1887), //PECA_
    ARQUIVAMENTO_CERTIDAO(1888), OFICIO_REN_PRAZO(1897), RECIBO_ENVIO_DOCUMENTOS_RECURSO(1900), LAC_SUINO(1901), LICENCA_AMBIENTAL_OPERACAO_AUTOMATICA(1902), SHAPEFILE_POLIG_DEJETOS(1913), LISTA_ALTERACAO_ESPECIES_ARVORES(1924), // 1904 base dev  1924 base prod
    AUA_AUTOMATICA(1925), ANALISE_ADMISSIBILIDADE(1927), AUDITORIA_DOCUMENTAL(1930), AUDITORIA_PRESENCIAL(1931), AUDITORIA_ESCLARECIMENTO(1932), AUDITORIA_OFICIO_SUSPENSAO(1933), OUTROS_ESCLARECIMENTOS_SOLICITADOS(1934), CONFIRMACAO_RECEBIMENTO_SOLICITACAO_ESCLARECIMENTOS(1937), AUTOMATICA_OFICIO_CANCELAMENTO(1938), AUTOMATICA_OFICIO_CONTINUIDADE(1939), AUDITORIA_OFICIO_ESCLARECIMENTO(1940), CONDICIONANTE(1943), PECA_DILATACAO_PRAZO(1946), //PECA_
    AUDITORIA_OFICIO_CANCELAMENTO(1947), AUDITORIA_OFICIO_CONTINUIDADE(1948), ARQUIVO_SHAPEFILE_PISCICULTURA(1949), RCE(1950), SHEPE_AREAS_SUPRESSAO(1973), SHEPE_AREAS_COMPENSACAO(1974), SHAPEFILE_TRECHO_CURSO_HIDRICO_APOS_RETIFICACAO(1980), PT_EMPREENDEDOR(2004), AUC_ASSINADA(2020), INDEF_AUC_ASSINADO(2021), SHAPEFILE_IMOVEL_MATRIZ(2024), SHAPEFILE_AREA_DESTINADA_RESERVA_LEGAL_DO_IMOVEL_MATRIZ(2025), SHAPEFILE_IMOVEL_RECEPTOR(2026), SHAPEFILE_AREA_DESTINADA_RESERVA_LEGAL_DO_IMOVEL_RECEPTOR(2027), SHAPEFILE_AREA_PROPOSTA_PARA_A_RESERVA_LEGAL(2028), ATA_CCLA_ASSINADA(2033), OFICIO_ENCAMINHAMENTO(2034), RCE_LAO(2035), EVENTO_ANEXO_DOCUMENTOS_AUDIT(2036), EVENTO_ALTERACAO_EQUIPE_AUDIT(2037), JUSTIFICATIVA_REL_VISTORIA(2038), LAUDO_MONITORAMENTO(2039), PECA_DATA_INICIO_JOBS(2058), PECA_DATA_FIM_JOBS(2059);

    public static final List<TipoDocumentoEnum> DOCUMENTOSFINAIS = Arrays.asList(LICENCA_ASSINADA, LAC_TPP, LAC_AVICULTURA, OFICIO_INDEFERIMENTO, CERTIDAO_OU_LICENCA, LICENCA_ASSINADA_DIGITALMENTE, OFICIO, LAC_SUINOCULTURA, LAC_SUINO, LICENCA_AMBIENTAL_OPERACAO_AUTOMATICA, AUA_AUTOMATICA);
    public static final List<Integer> INT_DOCUMENTOSFINAIS = Arrays.asList(1387, 1389, 1392, 1393, 1438, 1476, 1477, 1622, 1829, 1865, 1901, 1902, 1925);

    public static final List<TipoDocumentoEnum> SHAPES = Arrays.asList(ARQUIVO_SHAPEFILE, ARQUIVO_SHAPEFILE_PROJETO, SHAPEFILE_AREA_EMPREENDIMENTO, ARQUIVO_SHAPEFILE_EMPREENDIMENTO, SHAPEFILE_RRPN_ESTADUAL, SHAPEFILE_POLIG_LIMITES_IMOVEL, SHAPEFILE_POLIG_LIMITES_IMOVEL2, SHAPEFILE_POLIG_LIMITES_IMOVEL3, SHAPEFILE_POLIG_LIMITES_IMOVEL4, SHAPEFILE_POLIG_DEJETOS, ARQUIVO_SHAPEFILE_PISCICULTURA, SHEPE_AREAS_SUPRESSAO, SHEPE_AREAS_COMPENSACAO, SHAPEFILE_TRECHO_CURSO_HIDRICO_APOS_RETIFICACAO, SHAPEFILE_IMOVEL_MATRIZ, SHAPEFILE_AREA_DESTINADA_RESERVA_LEGAL_DO_IMOVEL_MATRIZ, SHAPEFILE_IMOVEL_RECEPTOR, SHAPEFILE_AREA_DESTINADA_RESERVA_LEGAL_DO_IMOVEL_RECEPTOR, SHAPEFILE_AREA_PROPOSTA_PARA_A_RESERVA_LEGAL);

    Integer valor;

    TipoDocumentoEnum(Integer valor) {
        this.valor = valor;
    }

    public Integer getValor() {
        return valor;
    }

    public static TipoDocumentoEnum valueOf(Integer valor) {
        for (TipoDocumentoEnum tpDoc : TipoDocumentoEnum.values()) {
            if (tpDoc.getValor().equals(valor)) {
                return tpDoc;
            }
        }
        return NAO_DEFINIDO_AINDA;
    }
}
